// 총기와 포스 패치 정의. 과학 개념 설명은 중학교 과학 「힘」 단원 내용을 기준으로 작성.

// 총기: 발로란트처럼 서 있으면 첫 발이 정확하고, 달리면서 쏘면 크게 빗나감.
// slot: primary 주무기 / secondary 보조무기 / melee 근접. price: 상점 가격(크레딧).
// falloff: [[거리(m), 피해 배율], ...] 멀어질수록 약해짐. ampBonus: 합력 강화장치로 더해지는 힘(N)
export const WEAPONS = {
  pistol: {
    id: 'pistol',
    slot: 'secondary',
    price: 0,
    name: '뉴턴 P-1',
    kind: '권총',
    auto: false,
    rpm: 400,
    damage: 26, // 머리 78
    headMult: 3,
    falloff: [[30, 0.85]],
    ampBonus: 4,
    magSize: 12,
    reserve: 36,
    reload: 1.75,
    draw: 0.45,
    speed: 280,
    spreadBase: 0.004,
    spreadMove: 0.03,
    spreadAir: 0.08,
    bloomPerShot: 0.012,
    bloomMax: 0.04,
    bloomRecover: 0.1,
    recoilPitch: [0.035],
    recoilYaw: [0.006, -0.005, 0.008, -0.007],
    recoilYawRand: 0.005,
    recoilMax: 0.12,
    recoilYawMax: 0.04,
    recoilRecover: 0.7,
    adsSpread: 0.6,
    adsRecoil: 0.85,
    adsZoom: 1.15,
    crouchSpread: 0.85,
  },
  sheriff: {
    id: 'sheriff',
    slot: 'secondary',
    price: 800,
    name: '줄 M-6',
    kind: '리볼버',
    auto: false,
    rpm: 240,
    damage: 55, // 머리 159
    headMult: 2.9,
    falloff: [[30, 0.85]],
    ampBonus: 8,
    magSize: 6,
    reserve: 24,
    reload: 2.25,
    draw: 0.6,
    speed: 320,
    spreadBase: 0.003,
    spreadMove: 0.06,
    spreadAir: 0.12,
    bloomPerShot: 0.03,
    bloomMax: 0.05,
    bloomRecover: 0.08,
    recoilPitch: [0.085],
    recoilYaw: [0.01, -0.012],
    recoilYawRand: 0.01,
    recoilMax: 0.2,
    recoilYawMax: 0.05,
    recoilRecover: 0.55,
    adsSpread: 0.6,
    adsRecoil: 0.85,
    adsZoom: 1.2,
    crouchSpread: 0.85,
  },
  shotgun: {
    id: 'shotgun',
    slot: 'primary',
    price: 900,
    name: '탄성 SG-12',
    kind: '산탄총',
    auto: false,
    rpm: 66,
    pellets: 12,
    pelletSpread: 0.075,
    damage: 17, // 한 알, 가까이서 몸통에 다 맞으면 204
    headMult: 2,
    falloff: [[8, 0.7], [12, 0.4]],
    ampBonus: 3,
    magSize: 5,
    reserve: 10,
    reload: 2.5,
    draw: 0.7,
    speed: 220,
    life: 0.12, // 산탄은 멀리 못 감 (약 26m)
    spreadBase: 0,
    spreadMove: 0.01,
    spreadAir: 0.04,
    bloomPerShot: 0,
    bloomMax: 0,
    bloomRecover: 1,
    recoilPitch: [0.08],
    recoilYaw: [0.015, -0.015],
    recoilYawRand: 0.01,
    recoilMax: 0.16,
    recoilYawMax: 0.05,
    recoilRecover: 0.5,
    adsSpread: 0.8,
    adsRecoil: 1,
    adsZoom: 1.1,
    crouchSpread: 0.95,
  },
  smg: {
    id: 'smg',
    slot: 'primary',
    price: 1600,
    name: '가속 SMG-9',
    kind: '기관단총',
    auto: true,
    rpm: 800,
    damage: 26, // 머리 78
    headMult: 3,
    falloff: [[20, 0.85]],
    ampBonus: 4,
    magSize: 30,
    reserve: 90,
    reload: 2.25,
    draw: 0.6,
    speed: 300,
    spreadBase: 0.006,
    spreadMove: 0.018, // 움직이며 쏴도 덜 빗나감
    spreadAir: 0.06,
    bloomPerShot: 0.004,
    bloomMax: 0.035,
    bloomRecover: 0.14,
    recoilPitch: [0.004, 0.007, 0.01, 0.012, 0.013, 0.012, 0.01],
    recoilYaw: [0, 0.004, -0.004, 0.006, -0.006, 0.008, -0.007],
    recoilYawRand: 0.006,
    recoilMax: 0.14,
    recoilYawMax: 0.07,
    recoilRecover: 0.7,
    adsSpread: 0.75,
    adsRecoil: 0.85,
    adsZoom: 1.15,
    crouchSpread: 0.85,
  },
  rifle: {
    id: 'rifle',
    slot: 'primary',
    price: 2900,
    name: '벡터 R-24',
    kind: '소총',
    auto: true,
    rpm: 585,
    damage: 40, // 머리 160 (어느 거리든 머리 1발)
    headMult: 4,
    ampBonus: 6,
    magSize: 25,
    reserve: 75,
    reload: 2.5,
    draw: 0.9,
    speed: 380,
    spreadBase: 0.0025, // 서서 쏜 첫 발은 거의 정확
    spreadMove: 0.07,
    spreadAir: 0.14,
    bloomPerShot: 0.0045,
    bloomMax: 0.035,
    bloomRecover: 0.16,
    // 연사 반동: 처음 3발은 거의 그대로, 그 뒤로 위로 올라감 (끊어 쏘면 정확)
    recoilPitch: [0.003, 0.006, 0.011, 0.016, 0.019, 0.02, 0.019, 0.017, 0.015, 0.013],
    recoilYaw: [0, 0.002, -0.002, 0.004, 0.006, 0.008, 0.005, -0.005, -0.009, -0.011, -0.007, 0.004, 0.009, 0.011, 0.007, -0.006],
    recoilYawRand: 0.005,
    recoilMax: 0.26,
    recoilYawMax: 0.1,
    recoilRecover: 0.7,
    adsSpread: 0.7,
    adsRecoil: 0.85,
    adsZoom: 1.25,
    crouchSpread: 0.8,
  },
  sniper: {
    id: 'sniper',
    slot: 'primary',
    price: 4700,
    name: '중력 OP-1',
    kind: '저격총',
    auto: false,
    scope: true, // 정조준 = 조준경 (화면 확대, 조준하지 않으면 크게 빗나감)
    rpm: 37.5,
    damage: 150, // 몸통 1발 (중량 방탄 포함 150)
    headMult: 1.7,
    ampBonus: 22,
    magSize: 5,
    reserve: 10,
    reload: 3.7,
    draw: 1.1,
    speed: 700,
    moveMult: 0.86,
    adsMoveMult: 0.45,
    adsRate: 4.5, // 조준경을 올리는 속도 (기본 7)
    spreadBase: 0.06,
    spreadMove: 0.1,
    spreadAir: 0.2,
    bloomPerShot: 0,
    bloomMax: 0,
    bloomRecover: 1,
    recoilPitch: [0.06],
    recoilYaw: [0.01, -0.01],
    recoilYawRand: 0.006,
    recoilMax: 0.14,
    recoilYawMax: 0.03,
    recoilRecover: 0.4,
    adsSpread: 0.02,
    adsRecoil: 1,
    adsZoom: 2.6,
    crouchSpread: 0.9,
  },
  knife: {
    id: 'knife',
    slot: 'melee',
    price: 0,
    name: '전술 나이프',
    kind: '근접',
    melee: true,
    draw: 0.3,
    light: { damage: 50, rate: 0.55, range: 2.1 },
    heavy: { damage: 80, rate: 1.0, range: 1.9 },
    backstabMult: 1.5,
  },
};

// 상점에 놓이는 순서 (보조무기 → 주무기 싼 것부터)
export const SHOP_WEAPONS = ['pistol', 'sheriff', 'shotgun', 'smg', 'rifle', 'sniper'];

// 방탄: 체력 앞에 붙는 보호막 (피해를 먼저 받음). 살아남으면 다음 라운드까지 남음
export const ARMOR = {
  light: { id: 'light', name: '경량 방탄', price: 400, value: 25 },
  heavy: { id: 'heavy', name: '중량 방탄', price: 1000, value: 50 },
};

// 거리에 따른 피해 배율
export function falloffAt(w, d) {
  let k = 1;
  for (const [at, mult] of w.falloff ?? []) if (d >= at) k = mult;
  return k;
}

export const PATCH_TIERS = {
  normal: { name: '일반', color: '#9db4cf' },
  special: { name: '특수', color: '#b59adf' },
  ultimate: { name: '필살', color: '#e3c26a' },
};

// 개인 장착 슬롯: C·Q = 일반, E = 특수, X = 필살
export const LOADOUT_SLOTS = [
  { key: 'C', tier: 'normal' },
  { key: 'Q', tier: 'normal' },
  { key: 'E', tier: 'special' },
  { key: 'X', tier: 'ultimate' },
];

export const PATCHES = {
  // ── 일반 ──
  gravityVeil: {
    id: 'gravityVeil',
    name: '중력 강화장막',
    tier: 'normal',
    cooldown: 18,
    duration: 3,
    radius: 5,
    short: '반경 5m 투사체 정지 · 3초',
    desc: '3초간 반경 5m 내 모든 투사체를 감속·정지시킨다. 종료 시 정지한 투사체는 낙하한다. 장막 내부에서는 아군 사격도 정지된다.',
    concept: '중력',
    conceptText: '지구가 물체를 지구 중심 방향으로 당기는 힘. 크기는 무게(단위 N)로 나타낸다. 장막 종료 후 투사체가 낙하하는 것은 중력 때문이다.',
  },
  elasticPad: {
    id: 'elasticPad',
    name: '탄성판',
    tier: 'normal',
    cooldown: 10,
    launchSpeed: 11,
    launchUp: 10,
    short: '조준 방향 고속 도약',
    desc: '발밑에 탄성판을 전개해 조준 방향으로 도약한다. 대형 컨테이너 상단 진입 가능.',
    concept: '탄성력',
    conceptText: '변형된 물체가 원래 형태로 복원하려는 힘. 변형시킨 힘의 반대 방향으로 작용하며, 변형이 클수록 커진다.',
  },
  resultantAmp: {
    id: 'resultantAmp',
    name: '합력 강화장치',
    tier: 'normal',
    cooldown: 18,
    duration: 5,
    short: '총기 공격력 +15% · 5초',
    desc: '5초간 총알에 같은 방향의 힘을 더한다 (벡터 R-24: 40 → 46). 경량 방탄 상대 몸통 4발 → 3발.',
    concept: '합력',
    conceptText: '두 힘이 같은 방향으로 작용하면 합력의 크기는 두 힘의 합이고, 방향은 두 힘의 방향과 같다. 40 N + 6 N = 46 N.',
  },
  reactionRounds: {
    id: 'reactionRounds',
    name: '작용·반작용 도탄',
    tier: 'normal',
    cooldown: 20,
    duration: 6,
    short: '탄 1회 반사 · 6초',
    desc: '6초간 발사한 탄이 벽·바닥에 맞으면 1회 반사된다(반사 후 위력 85%). 엄폐물 뒤 목표 공략용.',
    concept: '작용·반작용',
    conceptText: 'A가 B에 힘을 가하면 B도 A에 크기가 같고 방향이 반대인 힘을 가한다. 탄이 벽을 밀면 벽도 같은 크기의 힘으로 탄을 밀어낸다.',
  },
  buoyShield: {
    id: 'buoyShield',
    name: '부력 방패',
    tier: 'normal',
    cooldown: 24,
    duration: 10,
    hp: 220,
    width: 2.2,
    height: 2.0,
    short: '부유 방탄판 전개 · 10초',
    desc: '전방 2m에 떠 있는 방탄판을 전개한다. 내구도 220, 10초 유지. 양 팀의 탄을 모두 막는다.',
    concept: '부력',
    conceptText: '액체나 기체가 그 속의 물체를 위쪽으로 밀어 올리는 힘. 기체 속에서도 작용한다(풍선). 방탄판은 부력 장치로 공중에 떠 있다.',
  },
  // ── 특수 ──
  frictionZero: {
    id: 'frictionZero',
    name: '마찰 제로 필드',
    tier: 'special',
    cooldown: 28,
    duration: 6,
    radius: 5,
    range: 25,
    short: '마찰력 0 구역 · 6초',
    desc: '지정 지점(최대 25m)에 반경 5m 마찰력 0 구역을 6초간 생성한다. 구역 내 적은 정지·방향 전환 불가.',
    concept: '마찰력',
    conceptText: '접촉면에서 물체의 운동을 방해하는 힘. 운동 방향의 반대로 작용하며, 면이 거칠수록·무게가 클수록 커진다. 마찰력이 0이면 운동 상태가 유지된다.',
  },
  elasticNet: {
    id: 'elasticNet',
    name: '탄성 그물',
    tier: 'special',
    cooldown: 30,
    radius: 3.5,
    range: 20,
    holdTime: 1.2,
    throwSpeed: 9,
    throwUp: 6,
    short: '적 구속 후 튕겨냄',
    desc: '지정 지점(최대 20m)에 그물을 투척한다. 반경 3.5m 내 적을 1.2초간 구속한 뒤 바깥쪽으로 튕겨낸다.',
    concept: '탄성력',
    conceptText: '늘어난 그물은 원래 형태로 돌아가려 하며 붙잡은 물체를 밀어낸다. 많이 늘어날수록 미는 힘이 크다.',
  },
  weightScanner: {
    id: 'weightScanner',
    name: '무게 감지기',
    tier: 'special',
    cooldown: 30,
    radius: 28,
    duration: 4,
    short: '반경 28m 발걸음·총성 탐지 · 4초',
    desc: '바닥에 가해지는 힘을 감지한다. 4초간 반경 28m 내에서 달리거나 사격·착지한 적의 위치를 아군에게 표시. 걷거나 앉아 이동하는 적은 탐지 불가.',
    concept: '무게',
    conceptText: '무게는 물체에 작용하는 중력의 크기이며 단위는 N이다. 질량 1 kg인 물체의 무게는 약 9.8 N. 달릴 때 발은 몸무게보다 큰 힘으로 바닥을 민다.',
  },
  // ── 필살 ──
  gravityCollapse: {
    id: 'gravityCollapse',
    name: '중력 붕괴',
    tier: 'ultimate',
    radius: 8,
    range: 35,
    pullTime: 0.8,
    holdTime: 3,
    short: '적 견인·구속 3초',
    desc: '지정 지점(최대 35m)에 고중력 지점을 생성한다. 반경 8m 내 적을 끌어당겨 3초간 구속한다.',
    concept: '중력',
    conceptText: '질량을 가진 물체는 서로 끌어당긴다. 질량이 클수록 당기는 힘이 크다.',
  },
  resultantSurge: {
    id: 'resultantSurge',
    name: '합력 폭주',
    tier: 'ultimate',
    duration: 8,
    short: '분대 전원 공격력 +15% · 8초',
    desc: '생존한 아군 전원의 총기 공격력을 8초간 강화한다 (벡터 R-24: 40 → 46).',
    concept: '합력',
    conceptText: '여러 힘이 같은 방향으로 작용하면 합력은 각 힘의 합이 된다. 분대 전원의 화력을 한 방향으로 집중한다.',
  },
  frictionStorm: {
    id: 'frictionStorm',
    name: '마찰 폭풍',
    tier: 'ultimate',
    radius: 9,
    range: 40,
    duration: 7,
    short: '광역 이동 둔화 · 7초',
    desc: '지정 지점(최대 40m) 반경 9m를 7초간 고마찰 구역으로 만든다. 구역 내 적 이동 속도 70% 감소, 점프 불가.',
    concept: '마찰력',
    conceptText: '접촉면이 거칠수록 마찰력이 커져 운동을 크게 방해한다. 마찰력은 운동 방향의 반대로 작용한다.',
  },
};

export const PATCH_ORDER = [
  'gravityVeil', 'elasticPad', 'resultantAmp', 'reactionRounds', 'buoyShield',
  'frictionZero', 'elasticNet', 'weightScanner',
  'gravityCollapse', 'resultantSurge', 'frictionStorm',
];

export const patchesOfTier = (tier) => PATCH_ORDER.filter((id) => PATCHES[id].tier === tier);

// 합력 락픽 설명 (결과 화면·락픽 화면)
export const LOCKPICK_CONCEPT = {
  concept: '힘의 합성',
  conceptText:
    '같은 방향의 두 힘: 크기를 더한다. 반대 방향의 두 힘: 큰 힘에서 작은 힘을 뺀다. 합력의 방향은 큰 힘의 방향이다.',
};
