// 총기와 포스 패치 정의. 과학 개념 설명은 중학교 과학 「힘」 단원 내용을 기준으로 작성.

export const WEAPONS = {
  rifle: {
    id: 'rifle',
    slot: 1,
    name: '벡터 R-24',
    kind: '소총',
    auto: true,
    rpm: 600,
    damage: 24,
    headMult: 2,
    magSize: 25,
    reserve: 75,
    reload: 2.4,
    draw: 0.6,
    speed: 160, // 투사체 속력(m/s)
    spreadBase: 0.004,
    spreadMove: 0.045,
    spreadAir: 0.09,
    bloomPerShot: 0.005,
    bloomMax: 0.035,
    bloomRecover: 0.15,
    // 연사 반동 패턴 (발사 순서별 상하·좌우 반동, 라디안)
    recoilPitch: [0.006, 0.009, 0.012, 0.014, 0.015, 0.015, 0.014, 0.012, 0.01, 0.008, 0.007],
    recoilYaw: [0, 0, 0, 0, 0.002, 0.004, 0.006, 0.005, -0.003, -0.007, -0.009, -0.007, 0.003, 0.007, 0.009, 0.006, -0.004],
    recoilMax: 0.12,
    recoilYawMax: 0.05,
    recoilRecover: 0.32,
    adsSpread: 0.35,
    adsRecoil: 0.75,
    adsZoom: 1.35,
    crouchSpread: 0.75,
  },
  pistol: {
    id: 'pistol',
    slot: 2,
    name: '뉴턴 P-1',
    kind: '권총',
    auto: false,
    rpm: 400,
    damage: 20,
    headMult: 2,
    magSize: 12,
    reserve: 36,
    reload: 1.6,
    draw: 0.4,
    speed: 120,
    spreadBase: 0.005,
    spreadMove: 0.025,
    spreadAir: 0.07,
    bloomPerShot: 0.014,
    bloomMax: 0.035,
    bloomRecover: 0.12,
    recoilPitch: [0.022],
    recoilYaw: [0.004, -0.004, 0.003, -0.005],
    recoilMax: 0.07,
    recoilYawMax: 0.02,
    recoilRecover: 0.36,
    adsSpread: 0.6,
    adsRecoil: 0.8,
    adsZoom: 1.15,
    crouchSpread: 0.8,
  },
  knife: {
    id: 'knife',
    slot: 3,
    name: '전술 나이프',
    kind: '근접',
    melee: true,
    draw: 0.3,
    light: { damage: 50, rate: 0.55, range: 2.1 },
    heavy: { damage: 80, rate: 1.0, range: 1.9 },
    backstabMult: 1.5,
  },
};

export const WEAPON_ORDER = ['rifle', 'pistol', 'knife'];

export const PATCH_TIERS = {
  normal: { name: '일반', color: '#9db4cf' },
  special: { name: '특수', color: '#b59adf' },
  ultimate: { name: '필살', color: '#e3c26a' },
};

// 개인 장착 슬롯: C·Q = 일반, E = 특수, X = 필살
export const LOADOUT_SLOTS = [
  { key: 'C', tier: 'normal' },
  { key: 'Q', tier: 'normal' },
  { key: 'E', tier: 'special' },
  { key: 'X', tier: 'ultimate' },
];

export const PATCHES = {
  // ── 일반 ──
  gravityVeil: {
    id: 'gravityVeil',
    name: '중력 강화장막',
    tier: 'normal',
    cooldown: 18,
    duration: 3,
    radius: 5,
    short: '반경 5m 투사체 정지 · 3초',
    desc: '3초간 반경 5m 내 모든 투사체를 감속·정지시킨다. 종료 시 정지한 투사체는 낙하한다. 장막 내부에서는 아군 사격도 정지된다.',
    concept: '중력',
    conceptText: '지구가 물체를 지구 중심 방향으로 당기는 힘. 크기는 무게(단위 N)로 나타낸다. 장막 종료 후 투사체가 낙하하는 것은 중력 때문이다.',
  },
  elasticPad: {
    id: 'elasticPad',
    name: '탄성판',
    tier: 'normal',
    cooldown: 10,
    launchSpeed: 11,
    launchUp: 10,
    short: '조준 방향 고속 도약',
    desc: '발밑에 탄성판을 전개해 조준 방향으로 도약한다. 대형 컨테이너 상단 진입 가능.',
    concept: '탄성력',
    conceptText: '변형된 물체가 원래 형태로 복원하려는 힘. 변형시킨 힘의 반대 방향으로 작용하며, 변형이 클수록 커진다.',
  },
  resultantAmp: {
    id: 'resultantAmp',
    name: '합력 강화장치',
    tier: 'normal',
    cooldown: 18,
    duration: 5,
    bonus: 3,
    short: '소총 공격력 +3 · 5초',
    desc: '5초간 소총 공격력 +3 (24 → 27). 몸통 기준 제압 탄수 5발 → 4발.',
    concept: '합력',
    conceptText: '두 힘이 같은 방향으로 작용하면 합력의 크기는 두 힘의 합이고, 방향은 두 힘의 방향과 같다. 24 N + 3 N = 27 N.',
  },
  reactionRounds: {
    id: 'reactionRounds',
    name: '작용·반작용 도탄',
    tier: 'normal',
    cooldown: 20,
    duration: 6,
    short: '탄 1회 반사 · 6초',
    desc: '6초간 발사한 탄이 벽·바닥에 맞으면 1회 반사된다(반사 후 위력 85%). 엄폐물 뒤 목표 공략용.',
    concept: '작용·반작용',
    conceptText: 'A가 B에 힘을 가하면 B도 A에 크기가 같고 방향이 반대인 힘을 가한다. 탄이 벽을 밀면 벽도 같은 크기의 힘으로 탄을 밀어낸다.',
  },
  buoyShield: {
    id: 'buoyShield',
    name: '부력 방패',
    tier: 'normal',
    cooldown: 24,
    duration: 10,
    hp: 220,
    width: 2.2,
    height: 2.0,
    short: '부유 방탄판 전개 · 10초',
    desc: '전방 2m에 떠 있는 방탄판을 전개한다. 내구도 220, 10초 유지. 양 팀의 탄을 모두 막는다.',
    concept: '부력',
    conceptText: '액체나 기체가 그 속의 물체를 위쪽으로 밀어 올리는 힘. 기체 속에서도 작용한다(풍선). 방탄판은 부력 장치로 공중에 떠 있다.',
  },
  // ── 특수 ──
  frictionZero: {
    id: 'frictionZero',
    name: '마찰 제로 필드',
    tier: 'special',
    cooldown: 28,
    duration: 6,
    radius: 5,
    range: 25,
    short: '마찰력 0 구역 · 6초',
    desc: '지정 지점(최대 25m)에 반경 5m 마찰력 0 구역을 6초간 생성한다. 구역 내 적은 정지·방향 전환 불가.',
    concept: '마찰력',
    conceptText: '접촉면에서 물체의 운동을 방해하는 힘. 운동 방향의 반대로 작용하며, 면이 거칠수록·무게가 클수록 커진다. 마찰력이 0이면 운동 상태가 유지된다.',
  },
  elasticNet: {
    id: 'elasticNet',
    name: '탄성 그물',
    tier: 'special',
    cooldown: 30,
    radius: 3.5,
    range: 20,
    holdTime: 1.2,
    throwSpeed: 9,
    throwUp: 6,
    short: '적 구속 후 튕겨냄',
    desc: '지정 지점(최대 20m)에 그물을 투척한다. 반경 3.5m 내 적을 1.2초간 구속한 뒤 바깥쪽으로 튕겨낸다.',
    concept: '탄성력',
    conceptText: '늘어난 그물은 원래 형태로 돌아가려 하며 붙잡은 물체를 밀어낸다. 많이 늘어날수록 미는 힘이 크다.',
  },
  weightScanner: {
    id: 'weightScanner',
    name: '무게 감지기',
    tier: 'special',
    cooldown: 30,
    radius: 28,
    duration: 4,
    short: '반경 28m 적 탐지 · 4초',
    desc: '바닥에 가해지는 힘(무게)을 감지해 반경 28m 내 적 위치를 4초간 아군에게 표시한다. 벽 너머도 탐지.',
    concept: '무게',
    conceptText: '무게는 물체에 작용하는 중력의 크기이며 단위는 N이다. 질량 1 kg인 물체의 무게는 약 9.8 N이다.',
  },
  // ── 필살 ──
  gravityCollapse: {
    id: 'gravityCollapse',
    name: '중력 붕괴',
    tier: 'ultimate',
    radius: 8,
    range: 35,
    pullTime: 0.8,
    holdTime: 3,
    short: '적 견인·구속 3초',
    desc: '지정 지점(최대 35m)에 고중력 지점을 생성한다. 반경 8m 내 적을 끌어당겨 3초간 구속한다.',
    concept: '중력',
    conceptText: '질량을 가진 물체는 서로 끌어당긴다. 질량이 클수록 당기는 힘이 크다.',
  },
  resultantSurge: {
    id: 'resultantSurge',
    name: '합력 폭주',
    tier: 'ultimate',
    duration: 8,
    short: '분대 전원 소총 +3 · 8초',
    desc: '생존한 아군 전원의 소총 공격력을 8초간 +3 강화한다.',
    concept: '합력',
    conceptText: '여러 힘이 같은 방향으로 작용하면 합력은 각 힘의 합이 된다. 분대 전원의 화력을 한 방향으로 집중한다.',
  },
  frictionStorm: {
    id: 'frictionStorm',
    name: '마찰 폭풍',
    tier: 'ultimate',
    radius: 9,
    range: 40,
    duration: 7,
    short: '광역 이동 둔화 · 7초',
    desc: '지정 지점(최대 40m) 반경 9m를 7초간 고마찰 구역으로 만든다. 구역 내 적 이동 속도 70% 감소, 점프 불가.',
    concept: '마찰력',
    conceptText: '접촉면이 거칠수록 마찰력이 커져 운동을 크게 방해한다. 마찰력은 운동 방향의 반대로 작용한다.',
  },
};

export const PATCH_ORDER = [
  'gravityVeil', 'elasticPad', 'resultantAmp', 'reactionRounds', 'buoyShield',
  'frictionZero', 'elasticNet', 'weightScanner',
  'gravityCollapse', 'resultantSurge', 'frictionStorm',
];

export const patchesOfTier = (tier) => PATCH_ORDER.filter((id) => PATCHES[id].tier === tier);

// 합력 락픽 설명 (결과 화면·락픽 화면)
export const LOCKPICK_CONCEPT = {
  concept: '힘의 합성',
  conceptText:
    '같은 방향의 두 힘: 크기를 더한다. 반대 방향의 두 힘: 큰 힘에서 작은 힘을 뺀다. 합력의 방향은 큰 힘의 방향이다.',
};
